/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "./accordion"

figma.connect(
  Accordion,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=6-237",
  {
    props: {},
    example: (p) => <Accordion {...p}>Accordion</Accordion>
  }
)
