/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Button, buttonVariants } from "./button"

figma.connect(
  Button,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=1-85",
  {
    props: {},
    example: (p) => <Button {...p}>Button</Button>
  }
)
