/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Card, CardHeader, CardTitle, CardDescription, CardAction, CardContent, CardFooter } from "./card"

figma.connect(
  Card,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=4-462",
  {
    props: {},
    example: () => (
      <Card>
        <CardHeader>
          <CardTitle>Title</CardTitle>
        </CardHeader>
        <CardContent>Content</CardContent>
      </Card>
    )
  }
)
