/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandSeparator, CommandItem, CommandShortcut } from "./command"

figma.connect(
  Command,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=57-1305",
  {
    props: {},
    example: (p) => <Command {...p}>Command</Command>
  }
)
