/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { ContextMenu, ContextMenuTrigger, ContextMenuGroup, ContextMenuPortal, ContextMenuSub, ContextMenuRadioGroup, ContextMenuSubTrigger, ContextMenuSubContent, ContextMenuContent, ContextMenuItem, ContextMenuCheckboxItem, ContextMenuRadioItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuShortcut } from "./context-menu"

figma.connect(
  ContextMenu,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=12-393",
  {
    props: {},
    example: (p) => <ContextMenu {...p}>ContextMenu</ContextMenu>
  }
)
