/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { FormItem, FormLabel, FormControl, FormDescription, FormMessage, useFormField, Form, FormField } from "./form"

figma.connect(
  Form,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=4-5215",
  {
    props: {},
    example: (p) => <Form {...p}>Form</Form>
  }
)
