/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { HoverCard, HoverCardTrigger, HoverCardContent } from "./hover-card"

figma.connect(
  HoverCard,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=4-462",
  {
    props: {},
    example: (p) => <HoverCard {...p}>HoverCard</HoverCard>
  }
)
