/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Input } from "./input"

figma.connect(
  Input,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=4-5200",
  {
    props: {},
    example: (p) => <Input {...p}>Input</Input>
  }
)
