/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Label } from "./label"

figma.connect(
  Label,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=21-1142",
  {
    props: {},
    example: (p) => <Label {...p}>Label</Label>
  }
)
