/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Menubar, MenubarMenu, MenubarGroup, MenubarPortal, MenubarRadioGroup, MenubarTrigger, MenubarContent, MenubarItem, MenubarCheckboxItem, MenubarRadioItem, MenubarLabel, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubTrigger, MenubarSubContent } from "./menubar"

figma.connect(
  Menubar,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=8-325",
  {
    props: {},
    example: (p) => <Menubar {...p}>Menubar</Menubar>
  }
)
