/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuViewport, NavigationMenuLink, NavigationMenuIndicator, navigationMenuTriggerStyle } from "./navigation-menu"

figma.connect(
  NavigationMenu,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-764",
  {
    props: {},
    example: (p) => <NavigationMenu {...p}>NavigationMenu</NavigationMenu>
  }
)
