/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Popover, PopoverTrigger, PopoverContent, PopoverAnchor } from "./popover"

figma.connect(
  Popover,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-888",
  {
    props: {},
    example: (p) => <Popover {...p}>Popover</Popover>
  }
)
