/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Progress } from "./progress"

figma.connect(
  Progress,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-1649",
  {
    props: {},
    example: (p) => <Progress {...p}>Progress</Progress>
  }
)
