/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { RadioGroup, RadioGroupItem } from "./radio-group"

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-1679",
  {
    props: {},
    example: (p) => <RadioGroup {...p}>RadioGroup</RadioGroup>
  }
)
