/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { ScrollArea, ScrollBar } from "./scroll-area"

figma.connect(
  ScrollArea,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=20-1084",
  {
    props: {},
    example: (p) => <ScrollArea {...p}>ScrollArea</ScrollArea>
  }
)
