/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton } from "./select"

figma.connect(
  Select,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=8-302",
  {
    props: {},
    example: (p) => <Select {...p}>Select</Select>
  }
)
