/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Separator } from "./separator"

figma.connect(
  Separator,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-2142",
  {
    props: {},
    example: (p) => <Separator {...p}>Separator</Separator>
  }
)
