/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Slider } from "./slider"

figma.connect(
  Slider,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-2119",
  {
    props: {},
    example: (p) => <Slider {...p}>Slider</Slider>
  }
)
