/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption } from "./table"

figma.connect(
  Table,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=21-1392",
  {
    props: {},
    example: (p) => <Table {...p}>Table</Table>
  }
)
