/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./tabs"

figma.connect(
  Tabs,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=6-212",
  {
    props: {},
    example: () => (
      <Tabs defaultValue="tab1">
        <TabsList>
          <TabsTrigger value="tab1">Tab 1</TabsTrigger>
        </TabsList>
        <TabsContent value="tab1">Content</TabsContent>
      </Tabs>
    )
  }
)
