/* Auto-generated by scripts/generate-code-connect.js */

import React from "react"
import figma from "@figma/code-connect"
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "./tooltip"

figma.connect(
  Tooltip,
  "https://www.figma.com/design/NCOipUvDUDA81v5lvGrFrg?node-id=13-896",
  {
    props: {},
    example: () => (
      <Tooltip>
        <TooltipTrigger>Hover</TooltipTrigger>
        <TooltipContent>Tooltip</TooltipContent>
      </Tooltip>
    )
  }
)
